### ISSUE TITLE
How do I exit EMU

### ISSUE THREAD

**Issue by cryzlasm** [fireeye/flare-emu#14]
During the running of the script, there will be a case where the script is in an infinite loop, and then the script cannot be canceled at this time. How can I solve it?

![image](https://user-images.githubusercontent.com/20424580/57922827-2ac9c200-7890-11e9-868e-39bef1234074.png)

**Comment by cryzlasm** [comment]
In the case of not ending the process, because I want to see the log that has been run

**Comment by cryzlasm** [comment]
```python
g_objEmu = None
g_objTimer_StopEmu = None
NUM_TIMEOUT = 5 * 60      # 5分钟
def stopEmu():
    if g_objEmu != None:
        g_objEmu.stopEmulation()

g_objTimer_StopEmu = threading.Timer(NUM_TIMEOUT, stopEmu)
g_objTimer_StopEmu.start()

```

**Comment by jtbennett-fe** [comment]
You can set the "verbose" variable for your EmuHelper object to 1 to enable debug logging of all emulated instructions from flare-emu, or 2 to also enable logging of thread context for each emulated instruction. flare-emu uses the logging Python module: https://docs.python.org/2.7/library/logging.html. These logs will be printed even if you have to kill the IDA Pro process.

**Comment by cryzlasm** [comment]
Thanks
