### ISSUE TITLE
Submodule Use Case

### ISSUE THREAD

**Issue by osardar** [fireeye/flare-emu#16]
I've utilized `FLARE-EMU` in a project as a submodule to allow me to make modifications in which I can later potentially submit as PRs.  An included `__init__.py` file would prevent me from having to check for it within my scripts & create it if needed. Is this something that you could consider adding, or would you suggest an alternate workflow?

**Comment by jtbennett-fe** [comment]
For use with IDA Pro, it is recommended to copy the scripts to IDA Pro's python directory.
