### ISSUE TITLE
Iterate should target properly

### ISSUE THREAD

**Issue by net13200** [fireeye/flare-emu#19]
Hi,

The iterate function doesn't really iterate to the targeted line. I want to use it in cases where I want to use a hook in a certain line of code, and I want the program to iterate to it and activate the given hook. 
In the function's code, the target's x-refs that are jmp or call are added as targets, but the target itself is deleted. 
I think that the target's flow and paths should be added as well, since i want to hook the target, and not the line before it.

**Comment by jtbennett-fe** [comment]
Sorry for the delayed reply, I was on vacation. The iterate function is not meant to emulate its targets; it hands control to the user via the provided`targetCallback` parameter. If you wish to emulate the targets as well, you can do so from within your callback function.
