### ISSUE TITLE
Don't work well on python3.x and ida7.4.

### ISSUE THREAD

**Issue by wonderkun** [fireeye/flare-emu#20]
When running with python3, the following error has occurred:
----------------------------------------------------------------------------------------------------- 

  File "D:\software\ida7.4\python\flare_emu.py", line 1437, in reloadBinary
    self._buildStack()
  File "D:\software\ida7.4\python\flare_emu.py", line 2008, in _buildStack
self.uc.mem_write(self.stack - self.stackSize /
    2, "\x00" * self.stackSize)
  File "D:\software\python37\lib\site-packages\unicorn\unicorn.py", line 399, in mem_write
    status = _uc.uc_mem_write(self._uch, address, data, len(data))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

-------------------------------------------------------------------------------------------------- 
I suppose the function   `mem_write(address,data) ` need a bytes object not a str.

so, I try to fix it by :

```
    def _buildStack(self):
        self.stack = self.allocEmuMem(self.stackSize) + self.stackSize / 2
        # print("stack_size: ",self.stackSize)
        self.uc.mem_write(self.stack - self.stackSize /
                          2, b"\x00" * self.stackSize)
```  
but,it still not work.  

-------------------------------------------------------------------
  File "D:\software\ida7.4\python\flare_emu.py", line 281, in __init__
    self.reloadBinary()
  File "D:\software\ida7.4\python\flare_emu.py", line 1437, in reloadBinary
    self._buildStack()
  File "D:\software\ida7.4\python\flare_emu.py", line 2008, in _buildStack
    self.uc.mem_write(self.stack - self.stackSize /
    2, b"\x00" * self.stackSize)
  File "D:\software\python37\lib\site-packages\unicorn\unicorn.py", line 399, in mem_write
    status = _uc.uc_mem_write(self._uch, address, data, len(data))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

-------------------------------------------------------------------

why? Please help me.

**Comment by mothball187** [comment]
@wonderkun thank you for trying flare-emu! While it is not explicitly stated in the documentation, flare-emu does not support Python3 at this time. Please try it with Python2. If you need any guidance not already shared in the README, please feel free to reach out to me and I would be glad to assist you.

**Comment by jtbennett-fe** [comment]
@wonderkun thank you for trying flare-emu! While it is not explicitly stated in the documentation, flare-emu does not support Python3 at this time. Please try it with Python2. If you need any guidance not already shared in the README, please feel free to reach out to me and I would be glad to assist you.

**Comment by wonderkun** [comment]
Bytes and str objects are confused, So I make some modifications to support python3 . 

https://github.com/wonderkun/flare-emu

**Comment by jtbennett-fe** [comment]
@wonderkun thank you, this is fantastic! One issue, however: getEmuWideString was designed to provide you with the raw bytes of the discovered wide string, not the decoded string. This is to provide more flexibility for the API, I would prefer to leave it to the user to decide whether or not he wishes to decode the bytes. 

If you can update your fork to address this issue, and remove the debug logging lines you added, I would gratefully help test and accept a PR from you. If not, I would still eventually use your fork as a basis for updating the project for Python3 when I can dedicate more time to this project. Either way, thank you!

**Comment by wonderkun** [comment]
@jtbennett-fe  ok, I get it.   `getEmuString()` and  `getEmuWideString()` only return a bytearray. Leave it to the user to decode it to a string.   

But you must change the test code in the `tests/` folder. Because the bytearry object cann't convert to str automatically in python3.
