### ISSUE TITLE
How do you step-into functions

### ISSUE THREAD

**Issue by Naville** [fireeye/flare-emu#27]
Currently I uses:

``mu = eh.emulateRange(sVa, eVa, callHook=callHook,skipCalls=False)``
to start my emualtion.

I was able to hook calls just fine. However when I need to step-into functions in the binary, like ``call sub_xxx``, it just ends emulation.

My callback code is as following:

```
if funcName=="SOME_LIBRARY_FUNCTION":
# Do my hooks here
           pass
elif funcName.startswith("sub"):
            print(funcName)
            pass
else:
            print("Unhandled Call %s" %(funcName))
            eh.stopEmulation(userData)
```

**Comment by Naville** [comment]
Turning on verbose shows the execution halts at that sub call:'

```
00000001000XXXXX: BL              sub_1000YYYYY
sub_1000YYYYY
```
From the example I was under the impression that the engine would automatically step into that sub without special processing. Now I'm confused

**Comment by jtbennett-fe** [comment]
@Naville it should work the way you expected it to. I am uncertain as to why it stops emulation at the instruction you have shown. If you would like, I can try to help you debug the issue if you can share a sample and a test script demonstrating the issue.
