### ISSUE TITLE
Commit from 21st of September causes errors

### ISSUE THREAD

**Issue by alexander-pick** [fireeye/flare-emu#29]
I was trying to get the latest commit working on Linux and Windows but it seems to be broken:

if __name__ == '__main__':   
    print("start")
    eh = flare_emu.EmuHelper()
 error: Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "C:\Program Files\IDA Pro 7.5\python\flare_emu.py", line 284, in __init__
    self.reloadBinary()
  File "C:\Program Files\IDA Pro 7.5\python\flare_emu.py", line 1481, in reloadBinary
    self.writeEmuMem(segVA, segBytes)
  File "C:\Program Files\IDA Pro 7.5\python\flare_emu.py", line 682, in writeEmuMem
    data = data.encode('latin1')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 1: ordinal not in range(128)

**Comment by jtbennett-fe** [comment]
@alexander-pick I have been trying to keep support for Python 2 and Python 3, but some issues arose recently that caused me to make the decision to drop support for Python 2 and move forward with Python 3. I am sorry for the inconvenience, but please try this with Python 3 and let me know if that resolves it. Thanks for the report!

**Comment by alexander-pick** [comment]
Thanks for the info, I will give it a try and rolled back in the meantime. I used it like a week ago for the flare challenge and it worked fine ;)
My issues is that I have some own plugins I need to port over first before being able to switch to 3 but it seems it is finally the time for that.

**Comment by jtbennett-fe** [comment]
Awesome, glad to see it being used for FlareOn 👍 . I will close this issue, but please submit a new one if it is still not working for you with Python 3 when you get around to it.
