### ISSUE TITLE
UnicodeDecodeError when creating flare_emu.EmuHelper() (IDA 7.2, python 2.7)

### ISSUE THREAD

**Issue by OrangeDoggoo** [fireeye/flare-emu#31]
Whenever I try to do 
`eh = flare_emu.EmuHelper()` 
it gives me 
```
 error: Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "D:\IDA 7.2\python\flare_emu.py", line 284, in __init__
    self.reloadBinary()
  File "D:\IDA 7.2\python\flare_emu.py", line 1497, in reloadBinary
    self.writeEmuMem(segVA, segBytes)
  File "D:\IDA 7.2\python\flare_emu.py", line 682, in writeEmuMem
    data = data.encode('latin1')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 1: ordinal not in range(128)
```

Using IDA 7.2 with python 2.7

**Comment by jtbennett-fe** [comment]
Hello @OrangeDoggoo , the latest update to flare-emu made it compatible with Python 3 only. My apologies, but there were some issues that arose in trying to support both Python 2 and Python 3, so I decided to go with Python 3. You can use an older version of flare-emu from the repo if you need it now and can't update to Python 3 anytime soon: https://github.com/fireeye/flare-emu/tree/65eb34367b1f0401af57603478ee8311352ad2b6
