### ISSUE TITLE
Adding Support For Binary Ninja

### ISSUE THREAD

**Issue by the-wondersmith** [fireeye/flare-emu#34]
I've already laid everything out to add support for Binary Ninja to Flare Emu, but before I got too deep into it it occured to me that it'd be good to ask - there's no reason that doing so wouldn't be possible or feasible is there? I assume it was omitted due to simple lack of interest / perceived wide-spread usage not some unknown-to-me fundamental incompatibility.

**Comment by jtbennett-fe** [comment]
@the-wondersmith this would be a most welcome and appreciated improvement! I haven't used Binary Ninja personally, but as long as you can implement all the methods when subclassing the AnalysisHelper class then it should be fine. Please reach out to me if you have any questions.

**Comment by the-wondersmith** [comment]
@jtbennett-fe  I have several questions I'd like to run by you as I work on this, but I don't think a GitHub issue is necessarily the correct place for it. If it's cool with you I grabbed a quick [temporary email](mailto: jeknaridro@nedoz.com) so no one has to publicly post contact details. Would you email over and let me know the best way to get in touch with you?

**Comment by jtbennett-fe** [comment]
@the-wondersmith email sent!
