### ISSUE TITLE
emulateRange is not using the provided register value during emulation

### ISSUE THREAD

**Issue by nikhilh-20** [fireeye/flare-emu#35]
Hello,

I was using `flare-emu` for string decryption. I'm trying to use `emulateRange` to pass a value into the `ecx` register but it doesn't seem to be working. Here's a minimal script where the problem can be seen:

```
from __future__ import print_function

import flare_emu

TARGET_FUNCTION = "sub_1000D44A"

def emulateRange_inst_hook(unicornObject, address, instructionSize, userData):    
    print("[+] ecx: " + hex(flare_emu.EmuHelper().getRegVal("ecx")))    

if __name__ == '__main__':
    print("[+] Starting minimalistic example")
    myEH = flare_emu.EmuHelper()

    encoded_string = bytearray([0x5C, 0x66, 0x73, 0x79, 0x57, 0x6A, 0x71, 0x6A, 0x66, 0x78, 0x6A, 0x00])
    encoded_string_ptr = myEH.loadBytes(encoded_string)
    
    print("[+] Bytes loaded at " + hex(encoded_string_ptr))
    for data in myEH.getEmuBytes(encoded_string_ptr, len(encoded_string)):
        print(hex(data), end=' ')
    print('')

    myEH.emulateRange(myEH.analysisHelper.getNameAddr(TARGET_FUNCTION),
                      registers={"ecx": encoded_string_ptr},
                      instructionHook=emulateRange_inst_hook)
```

I was expecting the value of `ecx` in `emulateRange_inst_hook` to be the value of `encoded_string_ptr` during emulation. The value of `ecx` doesn't change throughout the emulated function, `sub_1000D44A`. The output shows that `ecx == 0`. I'm assuming that's because the code https://github.com/fireeye/flare-emu/blob/659400c47eb67b421f8e2cbac528a5a71b12c07d/flare_emu.py#L292 says `unspecified registers will be initialized to 0`. Here's the script output:

```
[+] Starting minimalistic example
INFO:flare_emu:initialized emulator for PE with X86 architecture in 32-bit mode
[+] Bytes loaded at 0x12000
0x5c 0x66 0x73 0x79 0x57 0x6a 0x71 0x6a 0x66 0x78 0x6a 0x0 
INFO:flare_emu:initialized emulator for PE with X86 architecture in 32-bit mode
[+] ecx: 0x0L
INFO:flare_emu:initialized emulator for PE with X86 architecture in 32-bit mode
[+] ecx: 0x0L
...
...
INFO:flare_emu:initialized emulator for PE with X86 architecture in 32-bit mode
[+] ecx: 0x0L
```

Any idea what I'm doing wrong here? Thanks!

**Comment by nikhilh-20** [comment]
The behavior is identical in both Py 2.7.18 and Py 3.7.0

**Comment by jtbennett-fe** [comment]
@nikhilh-20 thanks for reaching out! I believe the problem with your script is that you are instantiating a new EmuHelper object in your instruction hook rather than using the existing object. Instead of creating a new object to get the ecx register value, try using your existing EmuHelper object stored in userData['EmuHelper']. Let me know if that works for you.

**Comment by nikhilh-20** [comment]
That worked perfectly. Thanks @jtbennett-fe! flare-emu is a solid tool.
