### ISSUE TITLE
Is there a way to access ZF?

### ISSUE THREAD

**Issue by wanitaqing** [fireeye/flare-emu#37]
Hi, I am emulating some instructions and I have one instruction which is `test eax, eax`. 
I would like to check if ZF is set. I have tried to access the key 'zf' because I read that it is a type of flag register, but received this error `KeyError: 'zf'`. So, I would like to ask if there is a way to access ZF?

**Comment by williballenthin** [comment]
i dont see `zf`, `eflags`, nor `rflags` accessible here: https://github.com/fireeye/flare-emu/blob/master/flare_emu.py#L1046

@jtbennett-fe?

**Comment by jtbennett-fe** [comment]
**flare-emu** currently does not expose the **EFLAGS** register that contains the **Zero Flag (ZF)** bit you are looking for. You can access the Unicorn engine directly through the **flare-emu** `EmuHelper` object, though. You could do something like:

```
from unicorn.x86_const import *

eh = flare_emu.EmuHelper()
eflags = eh.uc.reg_read(UC_X86_REG_EFLAGS)
zf = (eflags >> 6) & 1 # ZF is the 6th bit
```

**Comment by wanitaqing** [comment]
Hi @jtbennett-fe. 

Thank you for the code example :) I managed to get the ZF! ^^
