### ISSUE TITLE
getPaths: Only find up to maxPaths

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-emu#7]
Currently `getPaths` calculates all possible paths through a function and then truncates them to `maxPaths`. Finding all paths for large and complex functions can take a very long time. Ideally, the function would shortcut the path exploration when `maxPaths` have been found.

**Comment by jtbennett-fe** [comment]
addressed in https://github.com/fireeye/flare-emu/commit/0cc6b0b73feba3ffdd83e0892b18b9b4fcbe0403
